version: '3.1'

services:

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: username
      MYSQL_PASSWORD: "pass"
    ports: 
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: pma
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1